# Generated by Django 4.1.5 on 2023-01-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_comment_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '주문 댓글', 'verbose_name_plural': '주문 댓글'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='shinhan_order_comment',
        ),
    ]
